implementationen af #121 i sprint 4
sw-bachelor/sw6 pull request #115
Opened 2019-05-20 07:58 UTC by jenspetur94

2019-05-20 08:09 UTC, Tekrus requested changes

2019-05-20 08:09 UTC, Moesgaarda commented on report/sections/sprint4/sprint-4-release.tex
> +There was one user story that was not completed before the release which  was assigned to group 12 and was about removing the back button from citizen mode as mentioned in \autoref{subsec:sprint-4-go
skriv noget om at da vi havde gjort det pisse smart, er det let at opdatere os, ved bare at ændre hvad der pr. default vises.

2019-05-21 08:29 UTC, andpaacoke commented
@jenspetur94 Har en del på noget af teksten så du må gerne læse det igennem igen 🤗

2019-05-21 12:19 UTC, Fatdet submitted a review, later dismissed

2019-05-22 07:36 UTC, Tekrus submitted a review, later dismissed

2019-05-22 07:38 UTC, andpaacoke submitted a review, later dismissed

2019-05-22 07:46 UTC, Eduardsen approved these changes

2019-05-22 07:47 UTC, andpaacoke approved these changes

2019-05-22 08:43 UTC, merged