Add changes in retrospect
sw-bachelor/sw6 pull request #48
Opened 2019-04-01 13:00 UTC by Fatdet

🦀 🐑 🏩 👶

2019-04-01 20:38 UTC, MathiasLybech submitted a review, later dismissed

2019-04-02 07:48 UTC, Eduardsen submitted a review, later dismissed

2019-04-02 07:53 UTC, Tekrus requested changes

2019-04-02 07:53 UTC, Moesgaarda commented on report/sections/sprint1/sprint-1-retrospective.tex
> +    \item Use the F-club's facilities as a more relaxed space for discussion.
```suggestion
    \item Use the F-Klubben's facilities as a more relaxed space for discussion. 
```

2019-04-02 07:53 UTC, Moesgaarda commented on report/sections/sprint1/sprint-1-retrospective.tex
> +These processes are described in \ref{subsec:SoS-sprint-planning} and \ref{subsec:SoS-sprint-introduction} respectively.
```suggestion
These processes are described in \autoref{subsec:SoS-sprint-planning} and \autoref{subsec:SoS-sprint-introduction} respectively.
```

2019-04-02 07:53 UTC, Moesgaarda commented on report/sections/introduction/scrum.tex
> +The start of the meeting takes the same form as the start of the sprint planning described in \autoref{subsec:SoS-sprint-planning}
```suggestion
The start of the meeting takes the same form as the start of the sprint planning described in \autoref{subsec:SoS-sprint-planning}.
```

2019-04-02 07:53 UTC, Moesgaarda commented on report/sections/sprint1/sprint-1-retrospective.tex
> +    \item More hack-a-thons.
```suggestion
    \item More hackathons.
```

2019-04-02 08:00 UTC, Eduardsen approved these changes

2019-04-02 08:07 UTC, MathiasLybech approved these changes

2019-04-02 08:23 UTC, Tekrus approved these changes

2019-04-02 08:24 UTC, merged