[WIP] Introduction and about giraf
sw-bachelor/sw6 pull request #8
Opened 2019-02-23 15:38 UTC by MathiasLybech

2019-02-25 15:29 UTC, Tekrus requested changes

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +GIRAF (Graphical Interface Resource for Autistic Folk) is a program developed for helping people with autism.
Lav eventuelt en list of terms i starten af rapporten hvor alle vores abbreviations kan findes.

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +It is primarily used to help with a visual representation of their daily and weekly schedule.
Tænker at den her med fordel kan sammensættes med sætningen før

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +Previous years has there also been developed different types of games and communication tools to help with education.
In the past development of the software.... something something

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +The program is developed by 6th semester students studying Software Engineering at Aalborg University.
Skal Software Engineering stå med stort?

Måske 6th semester software engineering students

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +The project has been passed on every year since 2011 with Ulrik Mathias Nyman as project coordinator.
Måske skrive det sammen med det ovenfor, og lave til at det er et ongoing project

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/about-giraf.tex
> +The customers are:
Tror gerne vi må skrive deres navne på, da det vil gøre det lettere når der bliver refereret til dem i interviews, evt bare fornavne

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/introduction.tex
> +In 2014 there were 16.8 occurences of the ASD diagnosis per 1,000, and around 1\% of all danes have an ASD diagnose\autocite{cdcdata}.
per 1,000 what?

approximately i stedet for about
Danes med stort
diagnosis

2019-02-25 15:29 UTC, Moesgaarda commented on report/sections/introduction/introduction.tex
> +As ASD is a spectrum disorder, each person with autism has different strengths and challenges.
måske mere konsistent med om ASD eller autism benyttes?

2019-02-26 15:51 UTC, Eduardsen submitted a review, later dismissed

2019-03-01 08:28 UTC, jenspetur94 commented on report/sections/introduction/about-giraf.tex
> +Different types of games and communication tools to help with education were implemented previously, but these functionalities have since been removed to focus on creating the ability to represent sc
Det er vel ikke grunden til at de ikke fungerer mere. 
Er grunden ikke at backenden blev reimplementeret sådan at de var imcompatible med den nye backend ?

2019-03-01 09:25 UTC, jenspetur94 submitted a review, later dismissed

2019-03-01 09:55 UTC, jenspetur94 approved these changes

2019-03-01 09:56 UTC, Tekrus approved these changes

2019-03-01 09:59 UTC, merged