[WIP]timeline for project
sw-bachelor/sw6 pull request #82
Opened 2019-05-02 11:14 UTC by MathiasLybech

Må gerne læses igennem. Der skal bare være en reference til rasmus' lort.

2019-05-03 09:58 UTC, jenspetur94 submitted a review, later dismissed

2019-05-03 10:50 UTC, Tekrus requested changes

2019-05-03 10:50 UTC, Moesgaarda commented on report/sections/introduction/timeline-for-project.tex
> +As there was no release at the end of sprint 1 because of the decision to migrate to Flutter, many of the user stories assigned in Sprint 1 were not completed and due to this there was no reason to c
```suggestion
As there was no release at the end of sprint 1 due to the decision to migrate to Flutter, several of the user stories assigned in Sprint 1 were not completed and as a result of this, there was no reason to conduct a usability test in sprint 1.
```

2019-05-03 10:50 UTC, Moesgaarda commented on report/sections/introduction/timeline-for-project.tex
> +Instead sprint 2 was mostly spent developing user stories planned in sprint 1 and some extra user stories for sprint 2.
```suggestion
Instead, sprint 2 was mostly spent developing user stories planned in sprint 1 and some additional user stories for sprint 2.
```

2019-05-03 10:50 UTC, Moesgaarda commented on report/sections/introduction/timeline-for-project.tex
> +This sprint ended with a usability test which are described in \todo{ref til rasmus' lort}
mere sigende todo pls

2019-05-03 10:50 UTC, Moesgaarda commented on report/sections/introduction/timeline-for-project.tex
> +Project handin was on May 28th.
```suggestion
Project hand in was on May 28th.
```

2019-05-06 11:49 UTC, jenspetur94 submitted a review, later dismissed

2019-05-07 07:36 UTC, Tekrus submitted a review, later dismissed

2019-05-07 07:41 UTC, jenspetur94 approved these changes

2019-05-07 07:44 UTC, Tekrus approved these changes

2019-05-07 07:44 UTC, merged