sprint 4 release
sw-bachelor/sw6 pull request #98
Opened 2019-05-15 09:47 UTC by andpaacoke

2019-05-15 10:06 UTC, Tekrus requested changes

2019-05-15 10:06 UTC, Moesgaarda commented on report/sections/sprint4/sprint-4-release.tex
> +The students that had worked on GIRAF the previous year had implemented an admin panel for web browsers. This had been broken earlier by some of the changes we had made to the backend/server. During
```suggestion
The students that had worked on GIRAF the previous year had implemented an admin panel for web browsers. This had been broken earlier by some of the changes we had made to the backend/server. During this sprint group sw612f19 got it working again, which meant that we once again could add guardians and citizens to the system. 
```

2019-05-15 10:08 UTC, Tekrus approved these changes

2019-05-16 08:36 UTC, MathiasLybech approved these changes

2019-05-16 08:37 UTC, merged